### PR TITLE
Merge upstream branch v0.23.0 into pingcap/provider-aws

### PR DESCRIPTION
**Pull request by tangenti**
The story of this started with Liyuan's persistence on the issue of CSI driver policies of the demo, which required a different set of APIs of the node groups that was introduced in a pretty late version of Crossplane. As nowadays people are blaming modifying CRDs directly on the dev env, the only choice seems to be to adopt the changes on our downstream.

After wasting several hours trying to only cherry-pick a few files related to the node groups, I found out that the complexity of the dependencies is far beyond the ability of my poor intelligence, so I decided to upgrade aggressively - so we got up-to-date APIs with a single PR, so no need for CPs over and over again. This proved to be way more difficult than I thought originally, mostly because of our unpreserved mania on laying out "what I want" on the codebase without carefully the possible debt of maintenance. 

Anyway, this tiny PR is done with the following steps:
1. git rebase -X theirs v0.23.0, which rebase our downstream changes onto the latest upstream version. The term "theirs" is a bit confusing here as it basically keeps our files - so the changes critical to our system won't be lost (and nobody wants to resolve those conflicts commit by commit)
2.  make it buildable. This is why we have the last commit (exclude the merge one), and this is the commit that our reviewers should really care about. 99% of those changes are made by simple regex replacement, with very few changes made manually by human beings (me). I'm pretty sure the test of controller/peering is broken as my gopls server crashes over and over again, I'll let Jiajin and Fangfang finish the mission impossible.

Please review the files that you care about or authored previously. Appreciated :) 

---

For reviewers' convenience, here is the link for the two commits that you should care about:

https://github.com/tidbcloud/provider-aws/pull/37/files/c880fc4091b09db07aa4bd0f7a6f0161a593c975..480577a1d1c252e909972923ccb43e38d91c17fb

### CODE REVIEW

**Review by hanlins — COMMENTED** [review]
Overall LGTM, I think one lesson we learned from this process is we should minimize the divergence from upstream, otherwise every time we need an upstream feature, we would need such a massive rebase. For our org specific changes, we can also try merge to upstream to minimize the gap.

Another issue is, do we really need to remove the unused CRs? @aylei @tennix @zjj2wry? Basically, if a CR is not used then we can just ignore it, but if we disable them in our fork, then this change can never be taken by upstream thus we have to keep out fork, what do you think?

**Comment by aylei** [comment]
Gorgeous...with the respect of all the efforts, I would still suggest another possibility that we run both the forked provider-aws and the upstream provider-aws simultaneously. The forked one continues to reconcile the currently used CRDs and the upstream one only reconcile the newly introduced ones. And we may gradually migrate the owner of CRDs from the forked one to the upstream one, until we completely offline the forked one. How do you like? @lorqor 

> 
> Another issue is, do we really need to remove the unused CRs? @aylei @tennix @zjj2wry? Basically, if a CR is not used then we can just ignore it, but if we disable them in our fork, then this change can never be taken by upstream thus we have to keep out fork, what do you think?

I agree we should keep the CRDs as is.

**Comment by lorqor** [comment]
> Gorgeous...with the respect of all the efforts, I would still suggest another possibility that we run both the forked provider-aws and the upstream provider-aws simultaneously. The forked one continues to reconcile the currently used CRDs and the upstream one only reconcile the newly introduced ones. And we may gradually migrate the owner of CRDs from the forked one to the upstream one, until we completely offline the forked one. How do you like? @lorqor
> 
> > Another issue is, do we really need to remove the unused CRs? @aylei @tennix @zjj2wry? Basically, if a CR is not used then we can just ignore it, but if we disable them in our fork, then this change can never be taken by upstream thus we have to keep out fork, what do you think?
> 
> I agree we should keep the CRDs as is.

Do we have any previous discussions on this topic? I don't carefully consider this option, but it seems the CRs provisioned by a controller can be managed by another controller, and they'll have different understanding and expectations on the CR (either change on the lifecycle logic or it could be different versions of APIs), also we'll have to carefully check the ownership of each CR which is another issue... I'm open to off-line discussion (especially this is a public repo...) if you're interested. 

I personally believe what we really need is:
1. Change the current model for the downstream. We should cherry-pick our changes onto the upstream branch, not the other way around. 
2. We make sure the test is not broken and we have proper test cases when our internal changes are added.

**Comment by lorqor** [comment]
For reviewers' convenience, here is the link for the two commits that you should care about:

https://github.com/tidbcloud/provider-aws/pull/37/files/c880fc4091b09db07aa4bd0f7a6f0161a593c975..480577a1d1c252e909972923ccb43e38d91c17fb

**Review by zjj2wry — APPROVED** [review]

**Pull request merged**
